apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "3"
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "World 100"
  traffic:
    - latestRevision: true
      percent: 100
      tag: blue
    # - latestRevision: false
    #   revisionName: hello-00001
    #   percent: 100
    #   tag: blue
    # - latestRevision: true
    #   percent: 0
    #   tag: green
